<?php

        $tablica = array(
                   array('id' => 'Afganistan', 'text' => 'Afganistan'),
                   array('id' => 'Albania', 'text' => 'Albania'),
                   array('id' => 'Algieria', 'text' => 'Algieria'),
                   array('id' => 'Andora', 'text' => 'Andora'),
                   array('id' => 'Angola', 'text' => 'Angola'),
                   array('id' => 'Anguilla', 'text' => 'Anguilla'),
                   array('id' => 'Antarktyka', 'text' => 'Antarktyka'),
                   array('id' => 'Antigua i Barbuda', 'text' => 'Antigua i Barbuda'),
                   array('id' => 'Arabia Saudyjska', 'text' => 'Arabia Saudyjska'),
                   array('id' => 'Argentyna', 'text' => 'Argentyna'),
                   array('id' => 'Armenia', 'text' => 'Armenia'),
                   array('id' => 'Aruba', 'text' => 'Aruba'),
                   array('id' => 'Australia', 'text' => 'Australia'),
                   array('id' => 'Austria', 'text' => 'Austria'),
                   array('id' => 'Azerbejdżan', 'text' => 'Azerbejdżan'),
                   array('id' => 'Bahamy', 'text' => 'Bahamy'),
                   array('id' => 'Bahrajn', 'text' => 'Bahrajn'),
                   array('id' => 'Bangladesz', 'text' => 'Bangladesz'),
                   array('id' => 'Barbados', 'text' => 'Barbados'),
                   array('id' => 'Belgia', 'text' => 'Belgia'),
                   array('id' => 'Belize', 'text' => 'Belize'),
                   array('id' => 'Benin', 'text' => 'Benin'),
                   array('id' => 'Bermudy', 'text' => 'Bermudy'),
                   array('id' => 'Bhutan', 'text' => 'Bhutan'),
                   array('id' => 'Białoruś', 'text' => 'Białoruś'),
                   array('id' => 'Boliwia', 'text' => 'Boliwia'),
                   array('id' => 'Bonaire', 'text' => 'Bonaire'),
                   array('id' => 'Bośnia i Hercegowina', 'text' => 'Bośnia i Hercegowina'),
                   array('id' => 'Botswana', 'text' => 'Botswana'),
                   array('id' => 'Brazylia', 'text' => 'Brazylia'),
                   array('id' => 'Brunei', 'text' => 'Brunei'),
                   array('id' => 'Bułgaria', 'text' => 'Bułgaria'),
                   array('id' => 'Burkina Faso', 'text' => 'Burkina Faso'),
                   array('id' => 'Burundi', 'text' => 'Burundi'),
                   array('id' => 'Chile', 'text' => 'Chile'),
                   array('id' => 'Chiny', 'text' => 'Chiny'),
                   array('id' => 'Chorwacja', 'text' => 'Chorwacja'),
                   array('id' => 'Curaçao', 'text' => 'Curaçao'),
                   array('id' => 'Cypr', 'text' => 'Cypr'),
                   array('id' => 'Czad', 'text' => 'Czad'),
                   array('id' => 'Czarnogóra', 'text' => 'Czarnogóra'),
                   array('id' => 'Czechy', 'text' => 'Czechy'),
                   array('id' => 'Dania', 'text' => 'Dania'),
                   array('id' => 'Demokratyczna Republika Konga', 'text' => 'Demokratyczna Republika Konga'),
                   array('id' => 'Dominika', 'text' => 'Dominika'),
                   array('id' => 'Dominikana', 'text' => 'Dominikana'),
                   array('id' => 'Dżibuti', 'text' => 'Dżibuti'),
                   array('id' => 'Egipt', 'text' => 'Egipt'),
                   array('id' => 'Ekwador', 'text' => 'Ekwador'),
                   array('id' => 'Erytrea', 'text' => 'Erytrea'),
                   array('id' => 'Estonia', 'text' => 'Estonia'),
                   array('id' => 'Etiopia', 'text' => 'Etiopia'),
                   array('id' => 'Falklandy', 'text' => 'Falklandy'),
                   array('id' => 'Fidżi', 'text' => 'Fidżi'),
                   array('id' => 'Filipiny', 'text' => 'Filipiny'),
                   array('id' => 'Finlandia', 'text' => 'Finlandia'),
                   array('id' => 'Francja', 'text' => 'Francja'),
                   array('id' => 'Gabon', 'text' => 'Gabon'),
                   array('id' => 'Gambia', 'text' => 'Gambia'),
                   array('id' => 'Ghana', 'text' => 'Ghana'),
                   array('id' => 'Gibraltar', 'text' => 'Gibraltar'),
                   array('id' => 'Grecja', 'text' => 'Grecja'),
                   array('id' => 'Grenada', 'text' => 'Grenada'),
                   array('id' => 'Grenlandia', 'text' => 'Grenlandia'),
                   array('id' => 'Gruzja', 'text' => 'Gruzja'),
                   array('id' => 'Guam', 'text' => 'Guam'),
                   array('id' => 'Guernsey', 'text' => 'Guernsey'),
                   array('id' => 'Gujana Francuska', 'text' => 'Gujana Francuska'),
                   array('id' => 'Gujana', 'text' => 'Gujana'),
                   array('id' => 'Gwadelupa', 'text' => 'Gwadelupa'),
                   array('id' => 'Gwatemala', 'text' => 'Gwatemala'),
                   array('id' => 'Gwinea', 'text' => 'Gwinea'),
                   array('id' => 'Haiti', 'text' => 'Haiti'),
                   array('id' => 'Hiszpania', 'text' => 'Hiszpania'),
                   array('id' => 'Holandia', 'text' => 'Holandia'),
                   array('id' => 'Honduras', 'text' => 'Honduras'),
                   array('id' => 'Hongkong', 'text' => 'Hongkong'),
                   array('id' => 'Indie', 'text' => 'Indie'),
                   array('id' => 'Indonezja', 'text' => 'Indonezja'),
                   array('id' => 'Irak', 'text' => 'Irak'),
                   array('id' => 'Iran', 'text' => 'Iran'),
                   array('id' => 'Irlandia', 'text' => 'Irlandia'),
                   array('id' => 'Islandia', 'text' => 'Islandia'),
                   array('id' => 'Izrael', 'text' => 'Izrael'),
                   array('id' => 'Jamajka', 'text' => 'Jamajka'),
                   array('id' => 'Japonia', 'text' => 'Japonia'),
                   array('id' => 'Jemen', 'text' => 'Jemen'),
                   array('id' => 'Jersey', 'text' => 'Jersey'),
                   array('id' => 'Jordania', 'text' => 'Jordania'),
                   array('id' => 'Kajmany', 'text' => 'Kajmany'),
                   array('id' => 'Kambodża', 'text' => 'Kambodża'),
                   array('id' => 'Kamerun', 'text' => 'Kamerun'),
                   array('id' => 'Kanada', 'text' => 'Kanada'),
                   array('id' => 'Katar', 'text' => 'Katar'),
                   array('id' => 'Kazachstan', 'text' => 'Kazachstan'),
                   array('id' => 'Kenia', 'text' => 'Kenia'),
                   array('id' => 'Kirgistan', 'text' => 'Kirgistan'),
                   array('id' => 'Kiribati', 'text' => 'Kiribati'),
                   array('id' => 'Kolumbia', 'text' => 'Kolumbia'),
                   array('id' => 'Komory', 'text' => 'Komory'),
                   array('id' => 'Kongo', 'text' => 'Kongo'),
                   array('id' => 'Korea Południowa', 'text' => 'Korea Południowa'),
                   array('id' => 'Korea Północna', 'text' => 'Korea Północna'),
                   array('id' => 'Kostaryka', 'text' => 'Kostaryka'),
                   array('id' => 'Kuba', 'text' => 'Kuba'),
                   array('id' => 'Kuwejt', 'text' => 'Kuwejt'),
                   array('id' => 'Laos', 'text' => 'Laos'),
                   array('id' => 'Lesotho', 'text' => 'Lesotho'),
                   array('id' => 'Liban', 'text' => 'Liban'),
                   array('id' => 'Liberia', 'text' => 'Liberia'),
                   array('id' => 'Libia', 'text' => 'Libia'),
                   array('id' => 'Liechtenstein', 'text' => 'Liechtenstein'),
                   array('id' => 'Litwa', 'text' => 'Litwa'),
                   array('id' => 'Luksemburg', 'text' => 'Luksemburg'),
                   array('id' => 'Łotwa', 'text' => 'Łotwa'),
                   array('id' => 'Macedonia', 'text' => 'Macedonia'),
                   array('id' => 'Madagaskar', 'text' => 'Madagaskar'),
                   array('id' => 'Majotta', 'text' => 'Majotta'),
                   array('id' => 'Makau', 'text' => 'Makau'),
                   array('id' => 'Malawi', 'text' => 'Malawi'),
                   array('id' => 'Malediwy', 'text' => 'Malediwy'),
                   array('id' => 'Malezja', 'text' => 'Malezja'),
                   array('id' => 'Mali', 'text' => 'Mali'),
                   array('id' => 'Malta', 'text' => 'Malta'),
                   array('id' => 'Mariany Północne', 'text' => 'Mariany Północne'),
                   array('id' => 'Maroko', 'text' => 'Maroko'),
                   array('id' => 'Martynika', 'text' => 'Martynika'),
                   array('id' => 'Mauretania', 'text' => 'Mauretania'),
                   array('id' => 'Mauritius', 'text' => 'Mauritius'),
                   array('id' => 'Meksyk', 'text' => 'Meksyk'),
                   array('id' => 'Mikronezja', 'text' => 'Mikronezja'),
                   array('id' => 'Mjanma', 'text' => 'Mjanma'),
                   array('id' => 'Mołdawia', 'text' => 'Mołdawia'),
                   array('id' => 'Monako', 'text' => 'Monako'),
                   array('id' => 'Mongolia', 'text' => 'Mongolia'),
                   array('id' => 'Montserrat', 'text' => 'Montserrat'),
                   array('id' => 'Mozambik', 'text' => 'Mozambik'),
                   array('id' => 'Namibia', 'text' => 'Namibia'),
                   array('id' => 'Nauru', 'text' => 'Nauru'),
                   array('id' => 'Nepal', 'text' => 'Nepal'),
                   array('id' => 'Niemcy', 'text' => 'Niemcy'),
                   array('id' => 'Niger', 'text' => 'Niger'),
                   array('id' => 'Nigeria', 'text' => 'Nigeria'),
                   array('id' => 'Nikaragua', 'text' => 'Nikaragua'),
                   array('id' => 'Niue', 'text' => 'Niue'),
                   array('id' => 'Norfolk', 'text' => 'Norfolk'),
                   array('id' => 'Norwegia', 'text' => 'Norwegia'),
                   array('id' => 'Nowa Kaledonia', 'text' => 'Nowa Kaledonia'),
                   array('id' => 'Nowa Zelandia', 'text' => 'Nowa Zelandia'),
                   array('id' => 'Oman', 'text' => 'Oman'),
                   array('id' => 'Pakistan', 'text' => 'Pakistan'),
                   array('id' => 'Palau', 'text' => 'Palau'),
                   array('id' => 'Palestyna', 'text' => 'Palestyna'),
                   array('id' => 'Panama', 'text' => 'Panama'),
                   array('id' => 'Papua-Nowa Gwinea', 'text' => 'Papua-Nowa Gwinea'),
                   array('id' => 'Paragwaj', 'text' => 'Paragwaj'),
                   array('id' => 'Peru', 'text' => 'Peru'),
                   array('id' => 'Pitcairn', 'text' => 'Pitcairn'),
                   array('id' => 'Polinezja Francuska', 'text' => 'Polinezja Francuska'),
                   array('id' => 'Polska', 'text' => 'Polska'),
                   array('id' => 'Portoryko', 'text' => 'Portoryko'),
                   array('id' => 'Portugalia', 'text' => 'Portugalia'),
                   array('id' => 'Republika Południowej Afryki', 'text' => 'Republika Południowej Afryki'),
                   array('id' => 'Republika Środkowoafrykańska', 'text' => 'Republika Środkowoafrykańska'),
                   array('id' => 'Republika Zielonego Przylądka', 'text' => 'Republika Zielonego Przylądka'),
                   array('id' => 'Reunion', 'text' => 'Reunion'),
                   array('id' => 'Rosja', 'text' => 'Rosja'),
                   array('id' => 'Rumunia', 'text' => 'Rumunia'),
                   array('id' => 'Rwanda', 'text' => 'Rwanda'),
                   array('id' => 'Salwador', 'text' => 'Salwador'),
                   array('id' => 'Samoa', 'text' => 'Samoa'),
                   array('id' => 'San Marino', 'text' => 'San Marino'),
                   array('id' => 'Senegal', 'text' => 'Senegal'),
                   array('id' => 'Serbia', 'text' => 'Serbia'),
                   array('id' => 'Seszele', 'text' => 'Seszele'),
                   array('id' => 'Sierra Leone', 'text' => 'Sierra Leone'),
                   array('id' => 'Singapur', 'text' => 'Singapur'),
                   array('id' => 'Słowacja', 'text' => 'Słowacja'),
                   array('id' => 'Słowenia', 'text' => 'Słowenia'),
                   array('id' => 'Somalia', 'text' => 'Somalia'),
                   array('id' => 'Sri Lanka', 'text' => 'Sri Lanka'),
                   array('id' => 'Stany Zjednoczone', 'text' => 'Stany Zjednoczone'),
                   array('id' => 'Sudan', 'text' => 'Sudan'),
                   array('id' => 'Surinam', 'text' => 'Surinam'),
                   array('id' => 'Syria', 'text' => 'Syria'),
                   array('id' => 'Szwajcaria', 'text' => 'Szwajcaria'),
                   array('id' => 'Szwecja', 'text' => 'Szwecja'),
                   array('id' => 'Tadżykistan', 'text' => 'Tadżykistan'),
                   array('id' => 'Tajlandia', 'text' => 'Tajlandia'),
                   array('id' => 'Tajwan', 'text' => 'Tajwan'),
                   array('id' => 'Tanzania', 'text' => 'Tanzania'),
                   array('id' => 'Togo', 'text' => 'Togo'),
                   array('id' => 'Tokelau', 'text' => 'Tokelau'),
                   array('id' => 'Tonga', 'text' => 'Tonga'),
                   array('id' => 'Trynidad i Tobago', 'text' => 'Trynidad i Tobago'),
                   array('id' => 'Tunezja', 'text' => 'Tunezja'),
                   array('id' => 'Turcja', 'text' => 'Turcja'),
                   array('id' => 'Turkmenistan', 'text' => 'Turkmenistan'),
                   array('id' => 'Uganda', 'text' => 'Uganda'),
                   array('id' => 'Ukraina', 'text' => 'Ukraina'),
                   array('id' => 'Urugwaj', 'text' => 'Urugwaj'),
                   array('id' => 'Uzbekistan', 'text' => 'Uzbekistan'),
                   array('id' => 'Watykan', 'text' => 'Watykan'),
                   array('id' => 'Wenezuela', 'text' => 'Wenezuela'),
                   array('id' => 'Węgry', 'text' => 'Węgry'),
                   array('id' => 'Wielka Brytania', 'text' => 'Wielka Brytania'),
                   array('id' => 'Wietnam', 'text' => 'Wietnam'),
                   array('id' => 'Włochy', 'text' => 'Włochy'),
                   array('id' => 'Wybrzeże Kości Słoniowej', 'text' => 'Wybrzeże Kości Słoniowej'),
                   array('id' => 'Wyspa Bożego Narodzenia', 'text' => 'Wyspa Bożego Narodzenia'),
                   array('id' => 'Wyspa Świętej Heleny', 'text' => 'Wyspa Świętej Heleny'),
                   array('id' => 'Wyspy Marshalla', 'text' => 'Wyspy Marshalla'),
                   array('id' => 'Wyspy Owcze', 'text' => 'Wyspy Owcze'),
                   array('id' => 'Wyspy Salomona', 'text' => 'Wyspy Salomona'),
                   array('id' => 'Zambia', 'text' => 'Zambia'),
                   array('id' => 'Zimbabwe', 'text' => 'Zimbabwe'),
                   array('id' => 'Zjednoczone Emiraty Arabskie', 'text' => 'Zjednoczone Emiraty Arabskie'),

        );

?>